version: '3.8'

services:
  pdf-service:
    build: .
    container_name: exam-portal-pdf-service-prod
    ports:
      - "8000:8000"
    environment:
      - PDF_SERVICE_PORT=8000
      - PDF_SERVICE_HOST=0.0.0.0
      - TEMPLATE_DIR=/app/templates
      - UPLOAD_DIR=/app/uploads
      - MAX_PAPER_SIZE=50MB
      - LOG_LEVEL=INFO
      - DEBUG=false
      - RELOAD=false
    volumes:
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
      - pdf_uploads:/app/uploads
      - pdf_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - exam-portal-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: pdf-service-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - pdf-service
    restart: unless-stopped
    networks:
      - exam-portal-network

volumes:
  pdf_uploads:
    driver: local
  pdf_logs:
    driver: local

networks:
  exam-portal-network:
    driver: bridge
